FROM python:3.10-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends default-jdk-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/default-java

RUN pip install --no-cache-dir --compile pandas numpy joblib findspark pyspark==3.5.7 kafka-python chronos-forecasting

COPY . .

CMD ["python", "app/bitola/main_program.py"]