FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir pandas kafka-python streamlit plotly

COPY . .

CMD ["streamlit", "run", "app/bitola/bitola_dashboard.py", "--server.address=0.0.0.0"]